/home/user/miniconda/envs/py36/lib/python3.6/site-packages/gym/logger.py:30: UserWarning: [33mWARN: Box bound precision lowered by casting to float32[0m
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
Traceback (most recent call last):
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/bayes_opt/target_space.py", line 191, in probe
    target = self._cache[_hashable(x)]
KeyError: (0.3753256340122696, 0.6482948408530079)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main_ac_mcc.py", line 258, in <module>
    n_iter=10,
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/bayes_opt/bayesian_optimization.py", line 174, in maximize
    self.probe(x_probe, lazy=False)
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/bayes_opt/bayesian_optimization.py", line 112, in probe
    self._space.probe(params)
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/bayes_opt/target_space.py", line 194, in probe
    target = self.target_func(**params)
  File "main_ac_mcc.py", line 102, in main
    state_space_samples = np.array([self.env.observation_space.sample() for x in range(1000)])
  File "main_ac_mcc.py", line 102, in <listcomp>
    state_space_samples = np.array([self.env.observation_space.sample() for x in range(1000)])
NameError: name 'self' is not defined
